version: "3.2"
services:
  ch-server-1:
    image: yandex/clickhouse-server
    volumes:
      - ./config.xml:/etc/clickhouse-server/config.d/local.xml
      - ./data/1:/var/lib/clickhouse
    ports:
      - 8123:8123
  ch-server-2:
    image: yandex/clickhouse-server
    volumes:
      - ./config.xml:/etc/clickhouse-server/config.d/local.xml
      - ./data/2:/var/lib/clickhouse
  ch-server-3:
    image: yandex/clickhouse-server
    volumes:
      - ./config.xml:/etc/clickhouse-server/config.d/local.xml
      - ./data/3:/var/lib/clickhouse
  ch-client:
    image: yandex/clickhouse-client
    entrypoint:
      - /bin/sleep
    command:
      - infinity
  zookeeper:
    image: zookeeper

